#- hosts: all
# become: true
# tasks: 
#    - name: delete old deployment
#       command: kubectl delete -f /home/ubuntu/Deployment.yml
#     - name: delete old service
#       command: kubectl delete -f /home/ubuntu/Service.yml


---
- name: Run kubectl get all command
  hosts: node
  gather_facts: no

  tasks:
    - name: Run kubectl get all
      command: kubectl get all
      register: result
    - name: Run kubectl apply
      command: kubectl apply -f /home/ubuntu/Deployment.yml
      register: result
    - name: Run kubectl apply
      command: kubectl apply -f /home/ubuntu/Service.yml
      register: result

