kind: Service                             
apiVersion: v1
metadata:
  name: aapservice
  labels:
    app: mrdevops
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31203
  selector:
    app: mrdevops                    
  type: NodePort                  
